[api.weather]
primary = "https://api.openweathermap.org/data/2.5/weather"
secondary = "https://api.weatherapi.com/v1/current.json"

[api.tourism]
primary = "https://api.opentripmap.io/0.1/en/places"
secondary = "https://www.triposo.com/api/20210317/location.json"

[api.restaurant]
primary = "https://api.yelp.com/v3/businesses/search"
secondary = "https://api.foursquare.com/v2/venues/search"

